# fly.toml app configuration file generated for icsct-fe-v1 on 2025-04-14T02:15:59+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'icsct-fe-v1'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
