# fly.toml file
app = "icsct-fe-v1" # Replace with your Fly.io app name

[build]
  builder = "heroku/buildpacks:20" # Use Heroku buildpacks for Node.js apps

[env]
  PORT = "8080" # Fly.io expects apps to listen on port 8080

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443